apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j
  namespace: webtree
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/dobs-csi-digitalocean-com
  name: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: neo4j
    namespace: webtree
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"
    volumeHandle: a0818a4a-81d8-11e9-b9db-0a58ac14d074
  storageClassName: do-block-storage
  volumeMode: Filesystem
