server:
  port: 9000

# GraphQL
#com.merapar.graphql:
#  rootQueryName: "queries"
#  rootQueryDescription: ""
#  rootMutationName: "mutations"
#  rootMutationDescription: ""
#  requestMapping:
#    path: "/v1/graphql"
#  executor:
#    minimumThreadPoolSizeQuery: 10
#    maximumThreadPoolSizeQuery: 20
#    keepAliveTimeInSecondsQuery: 30
#    minimumThreadPoolSizeMutation: 10
#    maximumThreadPoolSizeMutation: 20
#    keepAliveTimeInSecondsMutation: 30
#    minimumThreadPoolSizeSubscription: 10
#    maximumThreadPoolSizeSubscription: 20
#    keepAliveTimeInSecondsSubscription: 30

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: token/new
      refresh: refresh

spring:
  data:
    neo4j:
      uri: http://neo4j:password@localhost:7474
      driver: org.neo4j.ogm.drivers.http.driver.HttpDriver